### ISSUE TITLE
Gestione cassa da contabile: inserimento di un nuovo movimento

### ISSUE THREAD

**Issue by StefanoMenozzi** [Jazzo/iGruppi#20]
Provato a non inserire un campo durante l'inserimento di un nuovo movimento : se non metto descrizione mi genera messaggio di inserimento obbligatorio, se non metto la data, mi mette quella odierna, quindi per me ok, se non metto l'importo, mi chiede di inserirlo, quindi per me ok, se non metto l'utente mi genera un errore di codice e non mi mostra alcun warning.

Provato a generare problema inserendo numero con la virgola anziché il punto e viceversa, NON genera problema di codice.
Esempio : 200.00, ok accetta;   200,00 ok accetta, 

Provato ad effettuare successive modifiche dopo aver inserito il movimento , anche cambiando utente: nessun problema

Anche se non selezione nessun beneficiario mi genera un errore di codice.

I numeri negativi sono accettati senza problema

Allargherei invece il campo descrizione a video per permettere maggior agio nella visualizzazione quando si inserisce la causale.

**Comment by Jazzo** [comment]
Dovrebbe essere a posto, eventualmente riapri questo issue.
