### ISSUE TITLE
Contabile: Gestione Cassa -> funzione ORDINI DA CHIUDERE -> Ordine archiviato -> tasto Archivia

### ISSUE THREAD

**Issue by StefanoMenozzi** [Jazzo/iGruppi#21]
Gestione Cassa -> funzione ORDINI DA CHIUDERE -> Ordine archiviato -> tasto Archivia

Il tasto archivia mi sembra sarebbe più corretto chiamarlo "Vedi dettaglio"

Quando poi si apre il dettaglio se l'ordine è già stato archiviato e clicco su "Archivia" mi genera errore di codice

**Comment by Jazzo** [comment]
Puoi incollare qui l'errore di codice che ti dà perché a me non dà errore.

Il giorno 21 marzo 2015 12:28, Stefano Menozzi <notifications@github.com>
ha scritto:

> Gestione Cassa -> funzione ORDINI DA CHIUDERE -> Ordine archiviato ->
> tasto Archivia
>
> Il tasto archivia mi sembra sarebbe più corretto chiamarlo "Vedi dettaglio"
>
> Quando poi si apre il dettaglio se l'ordine è già stato archiviato e
> clicco su "Archivia" mi genera errore di codice
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jazzo/iGruppi/issues/21>.
>



-- 
Davide Gullo, Consulente Web (professionista disciplinato ai sensi della
legge 4/2013)
http://www.m4ss.net
gullo@m4ss.net

**Comment by Jazzo** [comment]
Ok, ho trovato l'errore e ho risolto.
Ora visualizza 2 pulsanti a seconda dello stato:
* Archivia (per gli ordini in stato "Consegnato" e ancora da archiviare)
* Visualizza dettaglio (per gli ordini già archiviati)

Per gli ordini da Archiviare pensavo di lasciare il pulsante "Archivia" in verde anche se in realtà c'è il passaggio alla visualizzazione del dettaglio.
Dici che crea confusione? Non vorrei non fosse un passaggio logico per tutti.

**Comment by Jazzo** [comment]
Rinominato il pulsante in "Visualizza e Archivia"

**Comment by monicapgiare** [comment]
Il pulsante così va bene, secondo me, però inserirei nel dettaglio anche il totale generale, non solo per utente.

Inoltre, anche qui, come nella gestione movimenti, nel dettaglio si vedono anche gli ordini degli utenti (anonimi) di altri gruppi che hanno partecipato all'ordine condiviso.
Nel caso di un ordine condiviso tra gruppi Giare potrebbe anche andar bene (e non sarebbe necessario che gli utenti fossero anonimi), ma tra gruppi diversi non credo.

![image](https://cloud.githubusercontent.com/assets/11527743/7141855/755a9958-e2d4-11e4-8ada-33559424419f.png)

**Comment by Jazzo** [comment]
Aggiunto Totale Ordine comprensivo di Spese Extra, utile anche per Tesoriere  (#45)
