### ISSUE TITLE
Problema Aggiungi/Sostituisci Referente Produttore

### ISSUE THREAD

**Issue by claudiogiare** [Jazzo/iGruppi#28]
La funzionalità di Aggiungi Referente (cioè avere più referenti per un produttore) al momento moltiplica i produttori.
3 referenti assegnati al produttore Collina= mi trovo 3 volte Collina tra i produttori disponibili nel gruppo.

In queste condizioni non funziona neanche più l'altra funzionalità del SOSTITUISCI REFERENTE

**Comment by claudiogiare** [comment]
![moltiplicazioneproduttori](https://cloud.githubusercontent.com/assets/7717889/6805078/6fd5fe12-d241-11e4-9da9-4d558683e03c.jpg)

**Comment by claudiogiare** [comment]
Inoltre forse questo problema ha generato l'impossibilità di aprire ordini per i referenti produttore, anche se i produttori hanno un solo referente interno.
Esempio:utente Valeria Iotti per Saponaria
![aperturaordine](https://cloud.githubusercontent.com/assets/7717889/6805185/f5d2df26-d241-11e4-858c-be1fd464e105.jpg)

**Comment by Jazzo** [comment]
Ho trovato l'errore, è solo una questione di visualizzazione errata (e verifica del permesso per il pulsante). I dati nel DB vengono scritti correttamente, sia in fase di UPDATE (Sostituisci Ref) che INSERT (Aggiungi Ref).

**Comment by Jazzo** [comment]
Risolto.
Resta però da ottimizzare l'aggiunta/sostituzione di un referente. Funziona ma dopo aver cliccato andrebbe aggiornata la combo con l'elenco dei produttori (eliminando la voce precedentemente selezionata).
